export * from './IMovie'
export * from './IUpcomingMovie'
export * from './IUpcomingResult'
export * from './ITransformedUpcomingResult'
export * from './IGenreResult'
export * from './ITransformedGenreResult'